
%let ekstra_lod = 6;
%let ekstra_vand = 6;

%let lod_ant = %sysfunc(sum(%eval(&antobs.),%eval(&ekstra_lod)));
%let vand_ant = %sysfunc(sum(%eval(&maxlen.),%eval(&ekstra_vand)));
%put &=lod_ant.;
%put &=vand_ant.;


data ekstra(keep=x rename=(x=ft));
length x $&vand_ant..;
set ct;
x = '***'||strip(ft)||'***';
run;

data top(drop=i);
length ft $&vand_ant..;
ft = repeat('*',%eval(&vand_ant.));

do i = 1 to 3;
output;
end;

run;

data bund(drop=i);
length ft $&vand_ant..;
ft = repeat('*',%eval(&vand_ant.));

do i = 1 to 3;
output;
end;

run;

data ct01;
set 
top
ekstra
bund;
run;


data ct02(drop=ft);
set ct01 end=eof;
retain %skriv_array_var(a=&lod_ant.,b=&vand_ant. ,at=gri , bt=d);

%skriv_array(navn=grid, type=$1.,a=&lod_ant.,b=&vand_ant. ,at=gri , bt=d);

do i = 1 to &vand_ant.;

grid{_n_,i} = substr(ft,i,1);

end;

if eof;
run;


data Part1/*(keeP=samlet_pris rename=(samlet_pris = Part1))*/;
length samlet_pris 8.;
set ct02;
%skriv_array(navn=grid, type=$1.,a=&lod_ant.,b=&vand_ant. ,at=gri , bt=d);
/*%skriv_array(navn=agrid, type=$1.,a=&lod_ant.,b=&vand_ant. ,at=agri , bt=d);*/
%skriv_array(navn=igrid, type=$1.,a=&lod_ant.,b=&vand_ant. ,at=igri , bt=d);

%skriv_array(navn=agrid, type=8,a=2,b=1000 ,at=agri , bt=d);

%skriv_array(navn=ogrid, type=$1.,a=&lod_ant.,b=&vand_ant. ,at=ogri , bt=d);

%skriv_array(navn=longgrid, type=$7.,a=&lod_ant.,b=&vand_ant. ,at=longgri , bt=d);


do lod = 1+3 to %eval(&LOD_ant.)-3;
	do vand = 1+3 to %eval(&vand_ant.)-3;
		ogrid{lod,vand} = grid{lod,vand}; 
	end;
end;

samlet_pris = 0;


/*do lod = 4;
	do vand = 4;
*/


do lod = 1+3 to %eval(&LOD_ant.)-3;
	do vand = 1+3 to %eval(&vand_ant.)-3;


	/*agrid bruges som tempomraade for indevaerende felt*/
		do alod = 1 to 2;
			do avand = 1 to 1000;

				agrid{alod,avand} = .;

			end;
		end;

		/*i igrid noter om felt er del af areal*/
		tal_agrid = 1;
		if igrid{lod,vand} = '' then do;

			igrid{lod,vand} = '+';
			agrid{1,tal_agrid} = lod;
			agrid{2,tal_agrid} = vand;

			/*loop hen over agrid, og udfyld samtidigt*/

			do mange = 1 to 1000;
				
				o = grid{agrid{1,1},agrid{2,1}};

				if o ne '' then do;

					do l = -1 to 1;
						do v = -1 to 1;
							if (abs(l)+abs(v) = 1) and grid{agrid{1,mange}+l,agrid{2,mange}+v} = o 
							and igrid{agrid{1,mange}+l,agrid{2,mange}+v} = ''  then do;

								tal_agrid+1;
								agrid{1,tal_agrid} = agrid{1,mange}+l;
								agrid{2,tal_agrid} = agrid{2,mange}+v;
								igrid{agrid{1,mange}+l,agrid{2,mange}+v} = '+';
								

							end;
						end;
					end;
				end;
				if agrid{1,mange+1} = . then leave;
			end;

			areal = 0;
			kanter = 0;

			do mange = 1 to 1000;

			longnavn = strip(put(agrid{1,1},8.))||'_'||strip(put(agrid{2,1},8.));

			


			

				if agrid{1,mange} ne . then areal+1;

				if agrid{1,mange} ne . then do;

				longgrid{agrid{1,mange},agrid{2,mange}} = longnavn;

				kant = 4;
					do l = -1 to 1;
						do v=-1 to 1;
							if abs(l)+abs(v) = 1 then do;
								if grid{agrid{1,mange}+l,agrid{2,mange}+v} = grid{agrid{1,mange},agrid{2,mange}} then kant = kant-1; 
							end;
						end;
					end;
					kanter = kanter + kant;
				end;

			end;
			/*put "areal: " areal;
			put "kanter: " kanter;*/
			pris = areal * kanter;

			samlet_pris = samlet_pris + pris;
			/*put "pris: " pris;
			put "samlet_pris: " samlet_pris;*/

		end;
	end;
end;

run;


data Part2/*Part2(keeP=samlet_pris rename=(samlet_pris=Part2))*/;
length samlet_pris 8.;
set Part1(keep=gri: longgri:)/*ct02*/;
%skriv_array(navn=grid, type=$1.,a=&lod_ant.,b=&vand_ant. ,at=gri , bt=d);
/*%skriv_array(navn=agrid, type=$1.,a=&lod_ant.,b=&vand_ant. ,at=agri , bt=d);*/
%skriv_array(navn=igrid, type=$1.,a=&lod_ant.,b=&vand_ant. ,at=igri , bt=d);

%skriv_array(navn=agrid, type=8,a=2,b=1000 ,at=agri , bt=d);
%skriv_array(navn=longgrid, type=$7.,a=&lod_ant.,b=&vand_ant. ,at=longgri , bt=d);

samlet_pris = 0;


/*do lod = 4;
	do vand = 4;*/


do lod = 1+3 to %eval(&LOD_ant.)-3;
	do vand = 1+3 to %eval(&vand_ant.)-3;


	/*agrid bruges som tempomraade for indevaerende felt*/
		do alod = 1 to 2;
			do avand = 1 to 1000;

				agrid{alod,avand} = .;

			end;
		end;

		/*i igrid noter om felt er del af areal*/
		tal_agrid = 1;
		if igrid{lod,vand} = '' then do;

			igrid{lod,vand} = '+';
			agrid{1,tal_agrid} = lod;
			agrid{2,tal_agrid} = vand;

			/*loop hen over agrid, og udfyld samtidigt*/

			do mange = 1 to 1000;
				
				o = grid{agrid{1,1},agrid{2,1}};

				if o ne '' then do;

					do l = -1 to 1;
						do v = -1 to 1;
							if (abs(l)+abs(v) = 1) and grid{agrid{1,mange}+l,agrid{2,mange}+v} = o 
							and igrid{agrid{1,mange}+l,agrid{2,mange}+v} = ''  then do;

								tal_agrid+1;
								agrid{1,tal_agrid} = agrid{1,mange}+l;
								agrid{2,tal_agrid} = agrid{2,mange}+v;
								igrid{agrid{1,mange}+l,agrid{2,mange}+v} = '+';
								

							end;
						end;
					end;
				end;
				if agrid{1,mange+1} = . then leave;
			end;

			areal = 0;
			kanter = 0;
			hj_ialt = 0;

			do mange = 1 to 1000;

				if agrid{1,mange} ne . then areal+1;

				hj = 0;
				if agrid{1,mange} ne . then do;
					
					oL = agrid{1,mange};
					oV = agrid{2,mange};
					
					
					/*inner courner*/ 


					if (grid{oL,oV} ne grid{oL,oV-1}) and (grid{oL,oV} ne grid{oL-1,oV})  then hj+1;
					if (grid{oL,oV} ne grid{oL,oV-1}) and (grid{oL,oV} ne grid{oL+1,oV})  then hj+1;
					if (grid{oL,oV} ne grid{oL+1,oV}) and (grid{oL,oV} ne grid{oL,oV+1})  then hj+1;
					if (grid{oL,oV} ne grid{oL-1,oV}) and (grid{oL,oV} ne grid{oL,oV+1})  then hj+1;

					/*in*/

					if (grid{oL,oV} = grid{oL,oV-1}) and (grid{oL,oV} = grid{oL-1,oV}) and (grid{oL,oV} ne grid{oL-1,oV-1})  then hj+1;
					if (grid{oL,oV} = grid{oL,oV-1}) and (grid{oL,oV} = grid{oL+1,oV}) and (grid{oL,oV} ne grid{oL+1,oV-1})  then hj+1;
					if (grid{oL,oV} = grid{oL+1,oV}) and (grid{oL,oV} = grid{oL,oV+1}) and (grid{oL,oV} ne grid{oL+1,oV+1})  then hj+1;
					if (grid{oL,oV} = grid{oL-1,oV}) and (grid{oL,oV} = grid{oL,oV+1}) and (grid{oL,oV} ne grid{oL-1,oV+1})  then hj+1;

				end;
				hj_ialt = hj_ialt + hj;
				


end;


			put "hj_ialt: " hj_ialt;

			put "areal: " areal;

			pris = areal * hj_ialt;

			samlet_pris = samlet_pris + pris;
			/*put "pris: " pris;
			put "samlet_pris: " samlet_pris;*/

		end;
	end;
end;

run;

data pr_grid(drop=v keep= v: );
set part2;

%skriv_array(navn=longgrid, type=$7.,a=&lod_ant.,b=&vand_ant. ,at=longgri , bt=d);

%macro pr;


%do b = 1 %to &lod_ant.;
%do a = 1 %to &vand_ant.;

v%eval(&a.) = longgrid{&b.,&a.};
*if v%eval(&a.) = -8 then v%eval(&a.)= .;


%end;
output;
%end;

%mend;
%pr;


run;

%macro slet;
data Part1(keeP=samlet_pris rename=(samlet_pris = Part1));
set ct02;
%skriv_array(navn=grid, type=$1.,a=&lod_ant.,b=&vand_ant. ,at=gri , bt=d);
%skriv_array(navn=agrid, type=$1.,a=&lod_ant.,b=&vand_ant. ,at=agri , bt=d);
%skriv_array(navn=igrid, type=$1.,a=&lod_ant.,b=&vand_ant. ,at=igri , bt=d);

samlet_pris = 0;

do lod = 1+3 to %eval(&LOD_ant.)-3;
	do vand = 1+3 to %eval(&vand_ant.)-3;


	/*agrid bruges som tempomraade for indevaerende felt*/
		do alod = 1+3 to %eval(&LOD_ant.)-3;
			do avand = 1+3 to %eval(&vand_ant.)-3;

				agrid{alod,avand} = '';

			end;
		end;

		/*i igrid noter om felt er del af areal*/
		
		if igrid{lod,vand} = '' then do;

			igrid{lod,vand} = '+';
			agrid{lod,vand} = grid{lod,vand};

			do mange = 1 to 1000; /*skriv som do until areal ikke skifter*/

				do alod = 1+3 to %eval(&LOD_ant.)-3;
					do avand = 1+3 to %eval(&vand_ant.)-3;
						if agrid{alod,avand} ne '' then do;

							do l = -1 to 1;
								do v=-1 to 1;

									if abs(l)+abs(v) = 1 then do;
	
										if agrid{alod,avand} = grid{alod+l,avand+v} then do;
	
											agrid{alod+l,avand+v} = agrid{alod,avand};
											igrid{alod+l,avand+v} = '+';
 
										end;
									end;
								end;
							end;
						end;
					end;
				end;
			end;

			areal = 0;
			kanter = 0;

			do alod = 1+3 to %eval(&LOD_ant.)-3;
				do avand = 1+3 to %eval(&vand_ant.)-3;
					if agrid{alod,avand} ne '' then areal+1;

						if agrid{alod,avand} ne '' then do;
							kant = 4;
							do l = -1 to 1;
								do v=-1 to 1;

									if abs(l)+abs(v) = 1 then do;

									if agrid{alod+l,avand+v} = agrid{alod,avand} then kant = kant-1; 
								end;
							end;
						end;	
						kanter = kanter + kant; 
					end;
				end;
			end;


			/*put "areal: " areal;
			put "kanter: " kanter;*/
			pris = areal * kanter;

			samlet_pris = samlet_pris + pris;
			/*put "pris: " pris;
			put "samlet_pris: " samlet_pris;*/

		end;
	end;
end;


run;

/*
data pr_grid(drop=v keep= v: );
set ct02;

%skriv_array(navn=grid, type=$1.,a=&lod_ant.,b=&vand_ant. ,at=gri , bt=d);

%macro pr;


%do b = 1 %to &lod_ant.;
%do a = 1 %to &vand_ant.;

v%eval(&a.) = grid{&b.,&a.};
*if v%eval(&a.) = -8 then v%eval(&a.)= .;


%end;
output;
%end;

%mend;
%pr;


run;
*/
/*
data pr_agrid(drop=v keep= v: );
set ct03;

%skriv_array(navn=agrid, type=$1.,a=&lod_ant.,b=&vand_ant. ,at=agri , bt=d);

%macro pr;


%do b = 1 %to &lod_ant.;
%do a = 1 %to &vand_ant.;

v%eval(&a.) = agrid{&b.,&a.};


%end;
output;
%end;

%mend;
%pr;


run;
*/
/*
data pr_agrid(drop=v vand keep= v: );
set ct03;

%skriv_array(navn=agrid, type=$1.,a=2,b=1000,at=agri , bt=d);

%macro pr;


%do b = 1 %to 2;
%do a = 1 %to 1000;

v%eval(&a.) = agrid{&b.,&a.};


%end;
output;
%end;

%mend;
%pr;


run;
*/

/*
data pr_agrid(drop=v keep= v: );
set ct03;

%skriv_array(navn=agrid, type=$1.,a=&lod_ant.,b=&vand_ant. ,at=agri , bt=d);

%macro pr;


%do b = 1 %to &lod_ant.;
%do a = 1 %to &vand_ant.;

v%eval(&a.) = agrid{&b.,&a.};


%end;
output;
%end;

%mend;
%pr;


run;
*/

data pr_igrid(drop=v keep= v: );
set ct03;

%skriv_array(navn=igrid, type=$1.,a=&lod_ant.,b=&vand_ant. ,at=igri , bt=d);

%macro pr;


%do b = 1 %to &lod_ant.;
%do a = 1 %to &vand_ant.;

v%eval(&a.) = igrid{&b.,&a.};
*if v%eval(&a.) = -8 then v%eval(&a.)= .;


%end;
output;
%end;

%mend;
%pr;


run;

%mend;

%macro skriv_array(navn=pris, type=,a= ,b= ,at= , bt=);

array &navn.{&a.,&b.} &type 
%do k=1 %to &a.;

&at.&k.&bt.1-&at.&k.&bt.&b.

%end;
;

%mend;

%macro skriv_array_var(a= ,b= ,at= , bt=);

%do k=1 %to &a.;

&at.&k.&bt.1-&at.&k.&bt.&b.

%end;

%mend;




data ct;
  infile datalines truncover;
  input  ft $20000.;
	
	retain lang 0;	

  	len = length(strip(ft));
	
	if len > lang then lang = len;

	call symput('antobs',strip(put(_N_,8.)));
	call symput('maxlen',strip(put(lang,8.)));

  datalines;
OOOBBBBXXXXXXXOOOOOOOAAAAAAAAAOOOOUUUUUUUUUUUUUUUUJJIFFFIIIIRRRRRRRRRRRRRRRRRRRRRNNNVVVVVVVVVVVPPPPPPPPPPPPPDDDDRRDDDDVVVVVVVVVVVGGVVGVVVVVV
OOBBBBBXXXXXXOOOOOOOOOAAAAAAOOOOOOUUUUUUUUUUUUUUUUJJIFIIIIIIIRRRRAAARRRRRRRRRRRRRRVVVVVVVVVVVVVVPNNNNPPGPPPPDDDDDDDDDVVVVVVVVVVVVGGGVGGVVVVV
OBBBBBBXXBXXOOOOOOOOOOAAAAAAOOOOOOUUUUUUUUUUUUUUUUJJIIIIIIIIRRRRAAAARRRRRRRRRRRRRRVVVVVVVVVVVVVFNNNNNPPGGPDDDDDDDDDDPPPVVPVVVVVVGGGGGGVVVVVV
BBBBBBBBBBOOOOOOOOOOOOAAAAAAOOOOOOOOUUUUUUUUUUUUUUUIIIIIIIIRRRAAAAAAARRRRRRRGRRRRRRRVVVVVVVVVVVFNNNNNNPGGGGDBBDDDDDDDPPPPPPVVVGGGGGGGGGVVVVV
ZZBBBBBBBBOOOOOOOOOOOOAAAAAAAOOOOOOOUUUUUUUUUUUUUIIIIIIIIIIIAAAAAAAAAARRARRRRRRBRRRVVVVVVVVVVVVVNNNNNNNNGGGBBBDDDDDDDPPPPPPPVVGGGGGGGGGGGVVV
ZZBBBBBBBOOOOOODOOOOOOAAAAIIIROROOOOUUUUUUUUUUUUUUXIIIIIIIIIAAAAAAAAAAAAAAARRRRRRRRRVVVVVVVVVVVVNNNNNGGGGGGGBBWWWDDDDPPPPPPPGGGGGGGGGGGGGGVV
ZZBBZBBBZOOOOOOOOOOOOOAAAAAIIRROOOOUUUPUUUUUUUUUUUIIIIIIIIIIAAAAAAAAAAADDAARRRRRRRRRRSVVVVVVVVNNNNNNNGGGGGGGGGWWDDDDDPYPPPPPGGGGGGGGGGSGJXXV
ZZZZZZZZZOOOOOOOOOOOOONNNAIIIIIIOOOPUUPPPUUUUUUPUIIIIIIIIIIIAAAAAAAAADADAAAAARRRRRRRRVVVVVVVVVNNNNNNNGGGGGGGWWWWDWDDDPPPPPPPPSSGGGGGGGGGXXXV
ZZZZZZZZZOOZNNOONNNONNNNNAIIIIIIIITPBBPPPPUUUUUPPIIIIIIIIIIAAAAAAAAAADDDAAAAARRRRRRRVVVVVVGVVVNNNNNNNNGGGGGWWWWWWWWDDPPPPPPPPGGGGGGGGGGXXXXX
ZZZZIZZIZZZZNNNNNNNOONNNNNZIIIIIIPPPPPPPPPPPPUPPIIIIIIIIIIIAAAAAAAAAADDDDAAARRRRRRRBVVVVVVGGVGGGNNNNNNGGGGWWWWWWWWWWWPPPPPPPPPPGGGGGGGXXXXXX
IIIIIIIIZZZZNNNNNNNNNNNNNIIIIIIIIIPPPPPPPPPPPJPPPIIIIIIIIIIIAAAAAAATDDDDDAARRRRRRRBBNNNVVVGGGGGGNNNNNNNGGGGWWWWWWWWWWWPPPPPPPPGGGGGGGGXXXXXX
IIIIIIIIIIZZNNNNNNNNNOONNNIIIIIIIIPPPPPPPPPPPPPPPIIIIIIIIIIIIIIICCCCDDDDDAARRRRRRBBBNNNNNVGGGGGGGGNNNRNGGGNNNWWWWWWWWWWWPPPPPPGGGGGGGXXXXXXX
IIIIIIIIIIZZBBBBNNNNOOOOONIIIIIIIIPQPPPPPPPPPPCCPPEIIIIIIIITTIIICCCCCAAAAAARRRRRRRBNNNNNNGGGGGGGGNNNNRNNNNNNNWWWWWWWWWWWPPPPPGGGPPGGXXXXXXXX
IIIIIIIIIZZZBBBBBNNNOOOOOIIIIIIIIIPPPPPPPPPPEPPPEEEIIIIIIIITTCCCCCCCCCACCCCRRRRAARBBANNNNGGGGGGGGRWNNNNNNNNNNWWWWWWWWWWWPPPPPPPPPPGGXXXXXXXX
FIIIIIIIEBBBBBBBBNNNNOOOOOIIIIIIIIIIIPPPPPPRPPPEEEEIIIIIITTUTVCCCCCCCCACCCKKRAAAARBAANAANGGGGGGGRRRRNNNNNNNPWWWWWWWWWWWWWWPPPPPPPXXXXXXXXXXX
FFFFFFIIIIIBBBBBNNNNNOOOOOIOOOIIIIIIIMMPPPPRRPPETTEEIIIITTTTTTCCCCCCCCCCCCKAAAAAAAAAAAAANGGGGRRRRRRRNNNNNNPPPWPWWWWWWWWUPPPPPPPPPXXXXXXXXXXX
FFFFUUIIIIIBBBBBRRROTOOOOOOOOOWQQQIIMMMMPPJRJEEETEEEITTTTTTTTTTCCCCCCCCCCCCPPAAAAAAAAAAARRRGGRRRRRRNNNNNNNNPPPPWWWWWWWWPPPJJPPPPPXXXXXXXXXXX
UUUUUUIIIBBBBBBBRROOOOOOOOOOOOQQQQQIMMMMPPJRJJEETEETTTTTTTTTTTTCCCCCCCCCCCCCAAAAAAAAAAAAAARRRRRRRRRNNNNNNNNPPPWWWWWWWPPPJJJJJPPPPPPPBXXXXXXX
RUUUUUIUUBBBBBBBRROOOOOOOOOOVQQQQQMMMMMMJPJJJJEETTTTTTTTTTTTTTTCCCCCCCCCCCCEEAMAAAAAAAAAAARRQRRRRRRNNNNNNNNPPPWWWWWWPPPPPJJJJPPPPPPBBBXXXXXX
UUUUUUUUUBBBBBBBRRRRORRRROOOQQQQQQMQQMJJJJJJJJEETTTTTTTTTTTTTTCCCCCCCCCCCEEEEAAAAAAAAAAAAARRRRRRRRRNNNNNNNNPPWWWWWPPPPPPJJJJPPPPPPPPPCXXXXXX
UUUUUUUUUBBBBBBRRRRRRRRROOOPQQQQQQQQQJJJJJJJJJEETTTTTTTTTTTTTCCCCCCCCCCCCCEEEEEAAAAAAAAAAAARRRRRRRRRNNNNNNNPPWWWWWPPPPPPPPPJPPPPCCCCCCXXXXXX
UUUUUUUUUUJBBJBRRRRRRRRXMMOPQQQQQQQQKJJJJJJJJJJJTTTTTTTTTTHHHCCCCCCCCCCCCHPEEEAAAAAAAAAAAAAARRRRRRRRNNNNNNNNBWWWWWPPPPPPPPPPPPPCCPCCCVVXXXXX
UUUUUUUUUUJJJJRRRRRRXXXXMMOPQQQQQQQQJJJJJJJJJJJJTTTTTTTTTTTTHCCCCCCCCCCCCCPEEAAAAAAAAAAAAVVVVRRRRRRRRNNNNNNNBWWBWBBPPPPPPPPPPPPEPPCCCCXXXXWC
UUUUUUUUUJJJJJRRRRRRXXXXXMQQQQQQQQQQQJJJJJJJJJJJTTTTTTTTTTTTHCCCCCCCCCCCCCPPEAAEAAASAAAAAVVVVVVVRRRRRNNVVNNNBBBBWBBBBPPPPPPPPPPPPPCCCCCXXWWW
UUUUUUUJJJJJJRRRRRRRRXXXXQQQQQQQQQQQQJJJJJJJJJJTTTTTTTTTTTPTEOOCCCCCCCCCPPPPEEEEAAASVVVVVVVVVVRRRRRRRNVVVIUNNBBBBBBBBBPPPPPPPPPPQPPCCCCWWWWW
UUUUUUUUUJJJJRRRRRRRRXXXXXIIQQQQQQQQQQJJJJJJJJJJJTTTTTTDDTPEEECCECSCCCCCPPPPEEEEAAAVVVVVVVVVVVVVVRRRRIIVIIUBBBBBBBBBPPPPPHPPPHPQQPCCCWWWWWWW
UUUUUUUUUJJJJRRRRRRRRXXXXXXXQQQQOQQQQYYJJJJJFGJJJTTTTTTTDTEEEEEEEECCCCCPPPPPPEEEEAAVVVVVVVVVVVVVRRRIRIIIIMBBBBBBBBBBBPPPPHHPPHHHQQQQWWWWWWWW
UUUUUUUUUUJJJJRRRRRRJJXXXXCXXQQQQYYQYYJJJJJJJGGGGGGTTTTTTEEEEEEEEECCCCPPPPPPPPEEEEEVVVVVVVVVVVVVRRIIIIIIIIIIIBBBBBBBBBBHHHHHHHDHQQWWQQWWWWWW
UUUUUUUJUJJGGGJJJJJJJJXXXXCKXQQQQYYYYJJJJJJJGGGGGGGTEEEEEEEEEEEEEUCCPPPPPPPPPPEEEEEEEVVVVVVVVVVVVRIIIIIIIIIIBBBBBBBBBBOHHHIIHHHJHWWWWWWWWWWW
UUUUUUJJJJJJGGJJJJJJJJJXMXKKKQDQQYYYYYYYYJJJJGGGGGGGEEEEEEEEEEEEEECCAPPPPPPPPPEEEEEEEVVVVVVLVLLLIIIIIIIIIIIIIBBBBBBPBOOHHHHHHHHHHWHWWWWWWWWW
UUKUUUUUUJJJGGJJMMMJMMMMMXXKKKDKKKYYYYYYYYPEJMMGGGEEEEEEEEEEEEEEECCCAAAAPPPPPPEEEEEEEVVVRVVLLLPPIIIIIIIIIIIIIVVVOOBBOOHHHHHHHHHHHHWWWWWWWWWW
KKKDUUUUUUJJGGJMMMPMMMMMMMKKKKKKKKYKYXYMMYPJJGGGGGGEEEEEEEEEEEEEECAAAAAPPPPPPPPEEEEEEEERRRVVLLPPFFIIIIIIIIIVVVVVOOOOOOOOHHHHHHHHHHHHHHWWWWWW
KDDDJJJUJJJJJJJMMMMMMMMMMMKKKKKKKKKKYXMMPYPPPPGGGEEEEEEEEEEEEEEZEAAAAAAAPPPPPPPEEEEEEEERRRSLLPPFFIIQIIIYYYYYVVVJVOOOOOOHHHHHHHHHHHHHHWWWWWWW
KDDDDDJJJJJJJGJMMMMMMMMMMMMKKKKKKKKXXXSMPPPPPPGGGEEEEEEEEEEEEEEZEAAAGGAAPPPAAAPEEEEEERRRRSSLPPPPPIIQIIIYYYYYYVVVVVOOOOOHHHHHHHHHHHHHWWWWWWWW
DDDDDDJJGJGJGGJJMMMMMMMMMMMMKKKKKKKXXSMMPPPPPPPPGGPEEEEEEEEEJEEEEAAAGGAAAAAAAAPEERERRRIRSSSPPPPPPPQQQYYYYYYYYVVVVVVVOOOHOTTTHTTTTTZHWWWWWWWW
DDDDDDDJGGGGGGJJMMMMMMMMMMMMKKKKXXXXXXMMMPPPPPPPPPPPEEEEEEEEJJJEEEAAGAAAAGGAAARRERRRRRRRSSSPPPPPPPPPPLYYYYYYVVVVVVVVDOOOOTTTTTTTTTZWWWWWWWWW
DDDEDDDGGGGGGJJJMMMMMMMMMMMMMKKKKXXXXXMMMPPPPPPPPPPPPEEEEJEEJJJJPEEGGGAGGGGGAAARRRRRRRZZZZPPPPPPPPPPPPYYYYYYVVVYYVVDDDOOOOOTTTTTZZZZWWZZWTTT
EEEEEEDGGGGGGGJJJMMMMMMMMMMOMKKKKKXXXXXLLPPPPPPPPPPPPEEJEJJJJJJJJGGGGGGGGGGGAARRRRRRRRRRPPPPPPPPPPPPPYYYYYYYGYYYDVDDDDDOOOOOTTTTOOOOWWZZZTTT
EEEEEEDGGGGGGGGJJMMMMMMMMMMMMKKKKKKKKAAAAYPPPPPPPPPPPEJJJJJJJJJJJGGGGGGGJGGAARRRRRRRRRRXXXPPPPPPPPPPPYYYYYYYYYYYYYYYYYYYYOOOOOOOOOOOCCZZZTTT
EEEEEEEGGGGGGGGMMMMMMMMMMRMMMKXKKAAAAAAAAPPPPPPAPPPQPPJJJJJJJJJJJGGGGGGGJJGGRRRRRRRRRRRXXPPPPPPPPPPPPYYYYYYYYYYYYYYYYYYYYYYOOOOOOOOCCCCZZZTT
EEMEEEGGGGGGGGGMMMMMMMMMXXXMKKXXKKKAAAAAAAAGPPPAAPPVVVVJJJJJJJJJJJGGGGGGGGGGRRRRRRRRRRRRRRPPPPPPPPPPYYYYYYYYYYYYYYYYYYYYYYYOOOOOOOOOCCCZZZZZ
EEMEEEEGGGGGGGMMMMMMMMMXXXXXXXXXKKKKAIAAAAAAPPAAAPAVVVVJJJJJJJJJJJJGGGGPGGMMMRRRRRRRRRRRRRRPPPPPPPYYYYYYYYYYYYYYYYDDDDOYYYYOOYYOOOZZCZCZZZZZ
EEMMEMGGGGGGGGGEEMMMAALXXXXXXXXXKKKKIIAAAAAAAAAAAPAVVVVJJJJJJJJJJJJGGGGPPPPPRRRRRRRRRRRRRRPPPPPPPPYYYYYYYYYYYYCYYYDDDDOYYYYYYYYOZZZCCZZZZZZZ
EEMMMMMGGGGGGGGEEEEEAAAGGGGGXXXXKIKIIIIIAAAAAAAAAAAVVVVJJJJJJJJJJGGGGGGPPPPPTTTRRRRRRRRRRRPPBBPPPPPYYYYYYYYYYYDDDZDDDDDYYYYYYYYZZZZZZZZZZZZZ
EMMMMMMMMGGKGRGREEEEEAAGGGGGXXXXKIIIIIIIAAAAJAJJAAAVVVVJJJJJJJJJJJJJGGPPPPVVVVTVVRRRRRRRRRRRRBPPPPPYYYLYYYYYYCCDDDDDDDYYYYYYYYYZZZZZZZZZZZZZ
MMMMMMMMMGKKKRRRREEEXAXGGGGGXXXXXXIIIIIIIAAJJJJJAAAAAAAAJJJJJJJJJJJJGPPPPPPVVVTVVRRRRRRRRRRRFBBPPPPQYYQQYYYYYYYBBDDDDYEYYYYYYYYZZZZZZZZZZZZZ
MMMMMMMMMMKKKRRRREEEXXXGGGGGXXXXXXIIIIIIIIIJJJJAAAAAACCJJJLXJJJJQJJJPPPPPPPVVVVVVRRRRRRRRRRRPPPPPPPQQQQQQYYYYYYBDDDDYYYWYYYYYYYYYYZZZZZZZZZZ
MMMMMMMMMKKKKRFRRRRXXXXGGGGGXXXXIIIIIIIIIIIIJJJJJAACCCCCAXXXXXJQQJXEXXPPPRPVVVVVRQQQQRRRRRRRRPPPUPBBQQQQQYYQQPPBBDDDYYYYYYYYYYYYYYZZZZZZZZZZ
MMMMMMMMMKKRRRRRRRRLXXXGGGGGXXXXXIIIIIJJJIJJJJJJJJJCCCCCXXXXQQQQQXXXXXPPPRRRVRRRRQQQRRRRRRRRPPPPPPQQQQQQQQQQPPPBBBBBYYYYYYYYYYYYYYZZZLZZZZZX
MMMMMMMMKKKKRRRRRRLLLXXGGGGGXXIIIIIIIIJJEIJJJJJJJJICCCCCCCXXQXQQQXXXTXPPPRRRRRRRRQQRRRRRRRRRRRRPPPBQQQQQQQQQPPPPPBBBBBYYYYYYYYYYFFZZZZZZXZXX
MMMMMMMMKKKKYRRRRRRRLLLGGGGGXXIIIIIJJJJJJQJJJJJJJFCCCCCCCCXXXXXQQQTTTXXXXWWRRRRRJRRRRRRRRRRRRRBBBBQQQQQQQQPPPPPPPPPPYYYYYYYYYYYYYFFTXXXXXZXX
MMMMMJMMKKKYYRRRRRRRRLLLLLXXXIIIIIIJJJJJJJJGGGGGGFFFCCCCCCXXXXXQQQTTTTXXXXRRRRRRJRRRRRRRRRRRRRBBBBQQQQQQQQQQPPPPPPPPPPYYYYYYYYYFFFFTXXXXXXXX
MMTTTJMMKKKYYOORRRRRLLLLLLXXIIIIIIJJJJJJGJGGGGGMMIFFSSCCCXXXXXXQQTTTTTTTDDJJRJJJJJJJJJRRRRRRRRBBQQQQQQQQQQQQPPPPPPPPPZZYYYYYYYFFTTTTTTTTXXXX
MMTTTMMMKKZZOOOORNLLLLLLLLLZZIZIZZEJJJJGGGGGGMMMMMMMSMMHHXXXXXXQQTTTTTTTTDJJJJJJJJJJJJJRRRRRRBBBQQQQQQQQQQQQPPPPPPPPPPZYYYYYYYYTTTTTTTTTXXXX
MTTTTGMZZZZZOOONNNLLLLLLLLZZZZZIZZZZJJJGGGZZMMMMMMMMMMMHMXXXXXTQTTTTTTTTTDJJJJJJJJJJJJJRRRRRBBBBQQQQQQQQQQQQQPPPPPPPPPYYYYYYYYYTTTTTTTTXXXXX
MMATTTZZZZZZYYYYYNLLLLLLLZZZZZZZZZZPPPZGGZZMMMZMMMMMMMMMMXXXXXTTTTTTTTTKKJJJJJJJJJJJJJRRBBBBBBBBBBEQQQQQQQHQMMPPPPPPUPTTTYTTYYYTTTTTTTTXXXXX
MMTTTKZZZZZZZYYYNNLLLLLLLLZZZZZZZZZZZZZZZZZZZZZMMMMMMMMXXXXXXXXZZTTTTTTTJJJJJJJJJXXJJJRRDDDBBBEEEEEEEMQQQQQQMPPPPPPPTTTTTTTTTTTTTTTTTTTTXXXX
MMMZZZZZZZZZZZZYNLLLLLLLDLLRRZZZZZZZZZZZZZZZZZMMMMMMMMXXXXXXXXXZZTTTTTTTJJJJJJJJXXXJJJXDDDDDDBEEEEEEEMQQMMMMMMPPPPBBUUTTTTTTTTTTTTTTTTTTTXXX
MMMMMZZZZZZZZZZZLLLLLLLDDRRRDZZZZZZZZZZZZZZZZMMDMMMMMMMXXXXXXXXXXSMTTTJJJJJJJJJXXXXXXJXXDDDDDEEEEMEMMMMMMMMMMMPMPBBBBBBBBTTTTTTTTTBBBTTTXXXX
MMMMMZZZZZZZZZZZLLLLLLLDDRDRDZZZZZZZZZMZZZZZMMZMMMMMMMWMXXXXXXXXXMMMMMJJJJJJJJJJXXXXXJXXDDDDDEEEEMMMMMMMMMMMMMMMMMBBBBBBBTTTTTTTBTTBBBTTXXXX
MMMMMZZZZZZZZZZZLLLLLLLDDDDDDDZZZZZZZZZZZZZZZZZMMMMMMMMMMXXXXXXXXMMJJJJJJJJJJJJXXXXXXXXDDDDEEEEEEEEMMMMMMMMMMMMMMMBBBBBTTTTTTTTBBBBBBYTXXXXX
MMMMZZZZZZZZZZZZLLLLNLDDDDDXDZZZZZZZZZIZZZZZZZZMMMMMMMMMMXXXXXXXMMMMBJJJJJJJJJJXXXXXXXXXDDDDDDDEEEMMMMMMMMMMMHMMMMMBBBBBTTTTTTBBBBBBBYBBXXXX
MMMMZZZZZZZZZZZZNNNNNBBDDDDDDZZZZZZZZZZZZZZZZZZMMFFMMMMMXXXXXXXXMMMMBJBBJJJJJJJJXXXXXXXXXXXXDDDDEEMMMMMMMMMMMHMMMMMBBBBNNNNTTTTBBBBBBBBBXXXX
MMOMMOOHZZZZUZZZZNNNBBBDDDDDDZZZZZZZZZGGGGGGZZZMFFFFFMMMXXXXRXOOMMMBBBBBJBBJJPJJXXXXXXXXXXXDDDDDEMMMMMMMMMMMMHHMMNNNBBBNNNXTTTTBBBBBBBBXXXXX
MMOOOOOOOIZZIZZNNNNBBBBBDDDBBBZZZZZBBZGGGGGGZZZFFFFXXMMOOXXXXXXOOBBBBBBBBBBJJJJJEEXXXXXDDDDDDDDDDMMMMMMMMMMBHHHHMNNNNNBNNNXTTTTTBBBBBBBBBBXX
OMOOOOOOOIIIIZZNNNNBBBBBDDBBBBZZZZZBZZGGGGGGZZZZFLFFMMOOOOOXXOOOOBBBBBBBBBBBJJEEEEEEXLLLDLDDZZDDDMMMMMMMMMHHHHHHHNNNNNNNNNXXXXBBBBBBBBBBBBXX
OOOOOOOOOIIIIINNNNNBBBBBBDDDBBBBBBBBBZGGGGGGZZZZFFFFFFOOOOOXOOOOOBBBBBBBBBBBBEEEEELLLLLLLLLDZZZZMMMMMMMMMMMHHHHHHHHNNNNNNNNXXXXBBBBBBBBBBBNN
OOOOOOOOOIIIINNNNBBBBBBBBBBBBBBBBBBBZZGGGGGGZZZFFFFFFFFOOOOOOOOOBBBBBBBBBBBBBBEEEEEELLLLLLDDZZZZMMMMMMMMMMHHHHHHHHHHNNNNNNNXXXXXXBBBBBBBBBNN
OOOOOOOOOOIINNNNNNNBBBBBBBBBBBBBBGGGGGGGGGGGZZZFFFFFFFFOOOOOOOOOBBBBBBBBBBBBBBEEEEEELLLLLLDZZZZZZMMMMMMMMHHHHHHHHHHHHNNNNNNXXXXDDDBBBBBBBBNN
OOOOOOOOIIINNNNNNNBBBBGGGGGBBBBZBGGGGGGGRRZLFFFFFFFFFFFFOOOOOOOOBBBIBBBBBBBDDBEEEEEEELLLLDDZZZZZZMMMMMMMMHXHHHHHHHHHHNNNNNNNXXXXXDGBBBNBBNNN
OOOOOONNIIINNNNNNNNBBBRRRRGGGBBZZGGGGGGGRRZFFFFFFFFFFFFFFFOOOOOOOBBIBBBBBBDDDDDDEEEELLLLLDDZZZZZMMMMMMMMMPPHHHHHHHHQPNNNNNXXXXXXXDGBBBNNNNNN
ZOOOOOONNIINNNKKKKBBBBZRRRRGGGBBZGGGGGGGRRFFFFFFFFFFFFFFFMFOOOOOIIIIIIBBBDDDDDDDDEEELLLLLZZZZZZZZZMMMMMPPPPHHHHHHHPPPPNNXXXXXDDDDDDDDNNNNNNN
OOOOOOOONNIINNNKKKBBOOPPPPPPGBBBBGGGGGGGRRRFFFFFFFFFFFFFFFFOOOIIIIIIIIIIIGDDDDDDDDELLLLLEZZZZZZZZMMMMMMPPPPPPHHHPPPPPPNNPXXXXXDDDDDPDNNNNNNN
AAOOOOOONNNNNNKKKKKKKZPPPPPPGBBZZGGGGGGGGRRFFFFFFFFFFFOFFFFOOOIIIIIIIIIIDDDDDDDDDDDLLLLLLOZZZZZZZMMMMMMMMMPPPPPPPPPPPPPPPXXPXXDDDDDNNNNNNNNN
AAONNNNNNNNNNKKKKKKKKZPPPPPPGZZZZGGGGGGGGRRFFFFFFFFFFFOOFOFOOOOIIIIIIIVVVDDDDDDDDDDLLLLLLOOOOZZZZMMMMMMMMPPPPPPPPPPPPPPPPPPPPXDDDDDDDNNNNNNN
AAAINNNNDNDNNNKKKZZKZZPPPPPPGGGZZGGGGGGGGZRFRFFFFFFFOFOOOOOOOOOIIIIIIIIVVDDDDDDDDDYLLLYLLOOOOZJZZMMMMMMMMMPPPPPPPPPPPPPPPPPIPXDDDDDNNNNNNNNN
IIIIINNDDDDDNNNNNNZZPPPPPPPPGGGGZGGGGGGGGRRRRFFFFFFOOOOOOOOOOOOIIIIIIIIVVVDDDDDDDYYYYYYLLOOOOOOOOMMMMFFFMMPPPPPPPPPPPPPBPPIIIDDDDDNNNNNNNNNN
IIIIIDDDDDDDNNNNNZZZPPPPPPPPGGGGZGGGGGGGGQQQRQFFFFQOOOOOOOOOOOOIIIIIIIVVVVVVDDDDDEYYYYLLOOOOOOOOOMMMMFFFFMFPPPPPPPPPIIPBPPIIIIIDDNNNNNNNNNNN
IIIIIIIDDDDDNNNNNZZZPPPPPPPPGGGGLZZZZZGGGZQQQQFFFQQOQQOOOOOOOOOIIIIIIIVVVVVVVDDDEEEEYOOOOOOOOOOOOMMFFFFFFFFLFPPPPPPPPPPPIIIIDDIDDDNNNNNNNNNN
IIIIIIDDDDDDDDZZZPPPPPPPPPPPPPGZZZZZZZGGGZQQQQQQQQQQQQOOOOOOOOIIIIIIIVVVVVVVVVVDEEMMOOOOOOOOOOOOOOFFFFFFFFFFFFFFVVVPPPPPPPDDDDDDDDGNNNNNNNNN
IIIIIIDDDDDDDDZZZPPPPPPPPPPPPPGPZPPZZPGGGZQQQQQQQQOOOVOOOOOOOOOOIIIIIIIVVVVVVVVDMMMMOOOOOOOOOOOOODFFFFFFFFFFFFFFVVVPPPPPPPDDDDDDDDGGNGNNNNNN
IIIIIIDDDDDDDDZZZPPPPPPPPPPPPPGPPPPPPPGGGPQQQQQQQQQOOOOOOOOOOOOQIIIIIIIVVVVVVVVVEMMMOOOOOOOOOOOOFFFFFFFFFFFFFFFFVVVVPVPPDDDDDDGGDGGGGGGGNNNN
IIIDDIDDDDDDDDZZZPPPPPPPPPPPPPGPPPPPPPGGGQQQQQQQQOQOOOOOOOOOOOOQKIIIIZVVVVVVVVVEEEMMMMOOOOOOOOOFFFFFFFFFFFFFFFVVVVVVVVDDDDDDDDBGGGGGGGGGNNNN
IDDDDDDDDDDDDDDTTPPPPPPPPPPPPPPPPPPPPQQQQQQQQQQQQOOOOOOOOOOQOOQQQQQIICCCCCRVVVEEEEMMMMMMOOOOOOOOOFFFFFFFFFFFFVVVVVVVVVDDDDDDDBBBGGGGHHHGNAAA
DDDDDZDDDDDDDDTTTPPPPPPPPPPPPPPPVPVPPPPPPPQQQQQQQOOOOOOOOQQQOOQQQQQIICCCRRRREEEEEEEMMMMMMOOOOOOOOHFFFFFFFFFFFVVVVVVVVVVVDDDDDBBBGGGGHHHHAAAH
DZDDDZDZDDDDDDDTTPPPPPPPPPPPPPKVVVVVPPPPPPPPQQQQJNOOOMOOOQQQOOQQQQQCCCCCRRREEEEEEEEMMMMMOOOOOOOOHHHFFFFFFFVFVVVVVVVVVVVDDDDDDBBBGGGHHHHHAAAH
ZZZZZZZZDDDDDTTTTTTTZPPPPPPPPPVVVVVVVPPPPPPPJQQQJJJOOONNNQQQQQQQQCCCCCEECRREEEEEEEMMMMMMMMOOOOHHHHHFFFFFFFVVVVVVVVVVVVVDDDDDDBBBGBGHHHHFHHHH
ZZZZZZZZDDDDTTTTTTTZZZZZZKKKKKVVVVVVVVPPPPPPJJQBJJJJJJNQQQQQQQQQQCCCCCCCCCRREEEEEMMMMMMMOOOOKOHFFFFFFFFFFFVVVVVVVVVVVVVDDDDDBBBBBBHHHHHHHHHH
ZZZZZZZZDDDDDDDTOOOZZZZZZKKKKKVVVVVVVVPPPPPPJJJBJJJJJJNQQQQQQQQQQCCCCCCCRCRREEEMMMMMMMMMOMMMMMMMMDFFFFFFFFVVVVVVVVVVVVVDDDDDBBBBBBHHHHHHHHHH
ZZZZZZZZZDDDDDDDOZZZZZZZZKKVKVVVVVVVVVPPPPPPJJJJJJJJJJNQQQQQQQQQQCCCCCRRRRREEXXHMVMMMMMMMMMMMMMMMDFFFFFFFFVVVVVVVVVVDDVDDDDDDDDDDBHHHHHHHHHH
ZZZZZZZZZDDDDDDDOOZZZZZZZZVVVVVVVVVVVSPPPPPJJJJJJJJJJJQQQQQQQQQQQQQCCCRRRRREEXXXVVMMMMMMMMMMMMMMMMFFFZFFFFZVVVVVVVVVDDDDDDDDDDDDHHHHHHHHHHHH
ZZZZZZZZZDZDZDDOOZZZZZZZZZVVVVVVVVVVVSPPPPPJJJJJJJJJJJJJQQQQQQQQQQQNCCRRRRRRXXXXVMMMMMMMMMMMMMMMMMMZZZZZZZZVVVVVNVVDDDDDDDDDDDDHHHHHHHHHHHHH
ZZZZZZZZZZZZZDOOOOZZZZZZVVVVVVVVVVVVVPPPPPPJJJJJJJJJJJJJQQQQQQQQQQQCCCRRRRRXXXVVVMMBUUUUMMMMMMPMMZZZZZZZZZZZVVVVNVFDFFFDDDDDDDDDNHHHHHHHHHHH
ZZZZZZZZZZZZZZZZOOOOOOZZTTVVVVVVVVVVVPPPPPPJJJJJJJJJJJJJQQQQQQQQQQQRCRRRRRRFXVVVVMMUUUUUMMMMPPPPPZZZZZZZZZZZZFFFFVFFFFFFTTTDTTDNNNNHNHHHHHHH
ZZZZZZZZZZZZZZZZOOOOOOZTTTTVVVVVVVVVVJPPPPCJJJJJJJJJJJJJJQQQQQQQQQQRRRRRRFFFVVVVVMMUUUUUMMMMMPPPPZZPZPZZZZZFZFFFFFFFFFFFTTTTTTDNNNNNNHNHHHHH
ZZZZZZZZZZZZZPPZOIIOOOOIITTTTVVVVVVVVJWPPPCCJJJJJJJJJJJJJQQQQQQQQQQRRRFFFFFFFVVVVVVUUUUMMMMPMPPPPPPPPPPZZZZFFFFYFFFFFFFFTTTQTJNNNNNNNNNHNNHH
ZZZZZZZZZZZZZPPPPIIIOOOIIITTVVVVVVVVVWWWCCCCJJJJJJJJJJJJEENEQQQQRRRRRRFFFFFHFFFVVVUUUUUMMPMPPPPPPPPPPPZZZZZFFFFFFFFFFFFFFTTTNNNNNNNNNNNNNNHH
ZZZZZZZZZZZZPPPPPIIIIIIIIITTVVVVVVVVVVWWWCCCCJJJJJJJJJJEOEEEQQRRRRRRRRFFFFFFFFFUUUUUUUUMMPPPPPPPPPPPPPZZZZZZFFFFFFFFFFFTTTTKNNNNNNNNNNNNNHHH
ZZZZZZZZZZZPPPPPPIIIIIIIIIIVVVVVVVVVVVWWWWWWCJJJJJJJJJEEEEEEEQRRRRRRRRFFFFFFFFFFUUUUUUUUMPPPPPPPPPPPDPPZZZZZZFFFFFFFFFFFTTTNNNNNNNNNNNNNFHHH
ZZZZZZZZZZZZPPPPPIIIIIIIIIIMMVVVVVNVWWWWWWWWWJJJJLLLEEEEEEEEEERRRRRRRRFFFFFFFFFCEUUUUUUMMPPPPPPPPPPPPPZZZZZZZFFFFFFFFFFFTTTNTNNNNNNNNNNNNDHH
ZZZZZZZZZZZPPPPPPIPIIIIIIIIMMVPPVIWFWWWWWWWWWWLLLLLLLEEEEEEEEEERERRQQRFFFFFFFFFCEUEEEEUMPPPPPPPPPPPPPPPZZZZZZFFFFFFFFFFKTTTTTTNNNNNNNNNNNNHH
ZZZZZZZZZZZPPPPPPPPIIIIIIIIIMPPPPWWWWWWWWWWWWWLLLLEEEEEEEEEEEEEEEQQQQQFFFFFFFFCCEUCCEEPMPPPPPPPPPPPPPPZZZZZZZFFFFFFFFKKKKTKTTTTTNNNNNNNNVVVH
NNMZZZZZZPPPPPPPPPIIIIIIIIIIIPPPPWQQQQQWWWWWWLLLLLLLEEEEEEEEEEEEBBBQQQQFFFFFFPCCCCCCCCPPPQQQPKPPPPPPPPZZZZZZOFFKKFKKKKKKKKKTTTTTNNNNNNNNNVVV
NNMZZZZZPPPPPPPPPPIRRRIUURPPPPPPPWQQQQQWWWWWWLLLLLLLEEEEEEEEEEEBBQQQQQQUFUUFFFCCCCCCCCPCPQCQPPPPPPPPPPPZZZOOOFFFKKKKKKKKNKKTTTTTNNNNNNNVVVVV
NNMMMMZPPPPPPPPPPIIRRRRRRRPPPPPPPPQQQQQQQQWWWLLLLLLLEEEEEEEEEEEEEEEQQQQUUUUUUFCCCCCCCCCCCCCCCPZZZPPPZZZZZZOOOOOKKKKKKKKKKKKKTTTTTTTTVVVVVVVV
MMMMMMZZPUUPPPPPPPPRRRRRRRRRPPPPPPQQQQQQQQWWWWLLLLLLEEEEEEEEEEEEQQQQQQQQQUUUUCCCCCCCCCCCCCCCCZZZPPZPZZZOOOOOOOOKKKKKKKKKKKIKTTTTTTTTVVVVVVVV
MMMMMMMMUUPPPPPPPPPRRRRRRPPPPPPPPPQQQQQQQQQWQWLLLLLLEEEEEEEIEEEEQQQQQQQQUUUURRRRRRRRRRCCCCCCCZZZZZZZZZOOOOOOOOGKKKKKKKKKKIIKTTTTTTTVVVKKVEVV
MMMMMLMUUPPPPPPPPPRRRRRRPPPPPPPPPPQQQQQQQQQQQQQQQQLLEEEEEEEEEEEEEQQQQQQQUUUURRRRRRRRRRCCCCCCKKKKKKKZZZOOOOOOOKKKKKKKKKKKKRIKTTTTTTTVVVKKKEVV
MMMMMLMUUPPPPPPPPPPPRRRPPPPPPPPPOQQQQQQQQQQQQQQQQQLEEELEMMEEEQQQQQQQQQQIIIUURRRRRRRRRRCCCCHHKKKKKZZZOOOOOOOOOOKKKKKKKKKKKRRKTTTTTVVVEEEKEEEE
MMMMMMMXXPPTPPPPPPPRRRRPPPPPPPPPPQQQQQQQQQQQQQQQQQLEEELLLLLQQQQQQQIQQQIIIIIIRRRRRRRRRRCCHHHHKKKZZZZZZOOOOOOOOOKKKKKKKKKKKRRTTTTTTTVVEEEEEEEE
MMMMMXXXXXPTPPPPPPPPRRRPPPPPPPPPPQQSSSSSSSSQQQQQQLLLELLLLLLLGQQQQQIQIIIIIIIIRRRRRRRRRRCCHHHHKKKKKZAAAQQOOOOOOOKKKKKKKKKKRRRNRRLLRRVEEEEEEEEE
MMMMMMMMXXPXXPPXXPXCRRRPPPPPPPPPSSSSSSSSSSSQQQLLLLLLLLLLLLLQGQQQIIIIIIIIRRRRRRRRRRRRRRCCHHHHQQQKZZAAAAQQOOOOOOOOKKKKKKKRRRRRVRRRRRREEEEEEEEE
MMMMMMMXXXXXXXXXXXXRRRNPPPPPPPPPSSSSSSSSSSSQQQLLLLLLLLLLLLLLGQQIIIIIIIIIRRRRRRRRRRRRRRHHHHHHHHQQZZAAQQQQQOOOOOOOKKKKKKKRRRRRRRRRRRRREEEEEEEE
MMMMMMMMXXXXXXXXXXXXRRRPPPPPPPPPSSSSSSSSSSSQQQQLLLLLLLLLLLLGGGQVIIIIIIIIRRRRRRRRRRRRHCHHHHHHHHQQQQQQQQQQQOOOOOOOKKKKKKKRRRRRRRRRRRREEEEEEEEE
MMMMMMMXXXXXXXXXXXXXEEEEPPPPPPPPSSSSSSSSSSSQQQQLLLLLLLLLLLGGGGQVIILIIIIIRRRRRRRRRRRRHCHHHHHHHHHHHQQQQQQQQQYOOOOOOKKKKKKRRRRRRRRRRRCEEEEEEEEE
MMMMMMMXXXXXXXXXXXXHEEEEPPCCCCPPSSSSSSSSSDDRQQQFFFFLLLLLLLGGGGGHIIIIIIIIRRRRRRRRRRRRHHHHHHHHGGHHHQQQQQQQQYYOOOOOOKKKKKRRRRRRRRRRRRRRREEEEEEE
MMKKKMXXXXXXXXXXXXWHHHHHOPCCCCCCSSSSSSSSSDDDDDFFFFFLLLLLLLLGGGGHIHIIRRRRRRRRRRRRRRRRHHHHHHHGGGHHHQQQCQQQQYYYYOOHHKKKFKRRRRRRRRRRRRRRREEEEEEE
MMKKKMXXXXXXXXXXHHHHHHHOOPCSSSSSSSSSSSSSSDDDDFFFFFFLFLLLLLLLLGGHHHIIRRRRRRRRRRRRRRRRHHHHGGGGGGGGHQQQCCQYYYYYROOHHKKKKHHHRRRRRRRRRRRRYEEEEEEE
MMMKXXXXXXXXXXXXXHHHHHHHHCCSSSSSSSSSSSSSSDDDFFFFFFFFFLLLLLLLLLHHHIIIRRRRRRRRRRRRRRHHHHHGGGGGGGGCQQQCCQQYYYYYRYHHHHHHHHHHRRRRRRRRRRRRRREEEEEE
KKKKKXXXXXXXXXXXHHHHHHHCCCCSSSSSSSSSSSSSSDDDFFFFFFFFFLLLLLLBBBBHHHHIRRRRRRRRRRRRRRHHHHHGGAAGGGGCCCCCCCCYYYYYYYHHHHHHHHHHHRRRRRRRRRRRRRREEEEE
KXXXXXXXXXXXXSHHHHHHHHHHJJCSSSSSSSSSSSSDDDDDFFFTTTFFTLLMLLMMBBBBBBRRRRRRRRRRRRRRRRHHHHHHGGGGGGGCGCCCCCYYYYYYYYYHHHHHHHHHHRRRRRRRRRRRBEEEEEEE
KXXXXXXXXXXXAHHHHHHHSSSSSSSSSSSSSCCDDDSDDDDDDFFTTTTFTTMMLMMPBBBBBBRRRRRRRRRRRRRRRREEPPPGGGGGGGGGGCCCCCYYYYYYYYHHHHHHHTTTHRRRBBBBBBRBBEEEEEEE
KXXXXXXXDXXAAHHHHHHHSSSSSSSSSSSSSCCDDDDDDDDDTTTTTTTTTMMMMMMMTMBBBBRRRRRRRRRRRRRRRREHPPPGGGGGGGGGGGGCCYYYYYYYYYYHHHHHHTTHHHRRBBBBBBRBBEEEEEEE
KKKXXXAXXXAAAHHHHHHHSSSSSSSSSSSSSCCDDDDDDDDDTTTTTTTTTTTMMMMMMMBBBBRRRRRRRRRRRRIEEEEHPPPGGGGGPGGGGGGGGGYYYYYYYYYHHHHTTTTTHBBBBBBBBBBBBEEEEEEE
KKKKKXAAXAAHHHHHHHHHSSSSSSSSSSFCCCDDDDDDDDDTTTTTTTTTTMMMMMMMMMBBBBRRRRRRRRRRLEIEEEEEPPPAGGNNPPPDDGGCCCYYYYYCYYYHHHHHTTTTTBBBBBBBBBBBBBEEEEEE
LLKLKXAAAAAAAAHHHHHHHHHJJJJJJJCCCDDDDDDDDDDTTTTTTTTTTMMMMMMMMMMBMBRRRRRRRRRREEEEEEEEPPPGGNNPPPPPGGGCCCCCCYYCYCHHGGHGTTTTBBBBBBBBBBBBBBBEEEEE
LLLLLAAAAUUUUAAAHYHHHHHJJJJRJJJCDDDDDDDDDTTTTTTTTTTTTMMMMMMMMMMMMBRRRRRRRRRREEEEEEENPPPPPPPPPPKCCCCCCCCCCCCCYCHGGGGGTTTTVVBKBBBBBBBBBEEEEECC
LLLLAAAUUUUUUAUAAHHHHJJJJJJOJGJCDDDDDDLDTTQTTTTTTTTTTMMMMMMMMMMMBBBYYYYHYYYYEEEEPPPPPPPPPPPPPPKCCCCCCCCCCCCCCCCGGGGGGTTTTTTBBFBBBBBBEEEEECCC
LLLLLLUUUUUUUUUUAHHHJJJJJJJOGGGKKDKDDKLDDQQTTTTTTTTMMMMMMMMMMMMMYYYYYYYYYYYYYEEEPPPPPPPPPPPPPPKCCCCCCCCCCCCGGGGGGGGGGGTTTTFFBBBBBBBBEECCCCCC
LLLLLLLUUUUUUUUAAAAAAJJJJJOOOOOOKKKKKKKKKTTTTTTTMMMMMMMMMMMMMMYYYYYYYYYYYYYYEEEEPPPPPPPPPCNNDNNOOCCCCCCCCCCCGGGGGGGGGGTTTFFFFBBBBBBBBECCCCCC
LLLLLLUUUUUUUUUUUDAAJJJJOOOOOOOOOOKKKKKKKKTAMTMMMMMMMMMMMMMMMOYYYYYYYYYYYYYUEEEEPPPPPPPPPPPPPPPPPCCCCCCCCCCCCGGGGGGGGTTTTTTFBBBBBBBBHHCCCCCC
LLLLLUUUUUUUUUUDDDDDPJJJJJOOOOOOOOKKKKKKKKMMMMMMMMMNNNMNMMMMOOOKKKYYYFYYYYYUEEEEPPPPPPPPPPPPPPPPPOCCCCCCCCCCCOGGGGGGGGFFTTFFBBXBXBBHHHOZCCCC
LLLLLLUUUUUUUUUDUDPPPPJJJJOOOOOOOOKKKKKKKMMMMMMMMMMNNNNNNMMHOOKKYYYYYYOOYOOEEEEEPPPPPPPPPPPPPPPPPOCLLCCCCCCCCOOGGGGGGGFFTFFBBBXXXBHHHOOOCCCC
LLLLLLUUUUUUUUUUUPPPPLPPJJJOOOOOOOKKKKKKKMMMMMMMSMMNNNNRNOOOOOOKYOYYOOOOOOOEEEEEEEEEPPPPPPPPPPPPPRLLLLCCCCCCCOGGGGGGGGFFFFFFFBBXXXOOOOCCCOCC
LLLLUUUUUUUUUUUUUUPPPPPPJJOOOOOOOOKKKKKKMMMMMVMMMMMYNNNNNNQOOOOOOOYOOOOOOOOEEEEEEEEEPPPPFFFFFFFRRPLLLPPPPPCCPGGGGGPSSPPPFJJJJBBXOOOOOOOOOOOC
LLLLLLLUUUUUUUUUUUPPPPPPJJJOOOOOTTTKKKKKMMMMMVMNWNNNNNNNNNNOOOOOOOYOOOOOOOOEEEOEEEEOPPPPFKFFFFRRPPLPLPPPPPCPPPPPPPPPPPPPFFJJJJJXXOEOOOOOOCCC
LLLLLLUUUUUUUUUUUPPPPPPPJJOOOOOOTTTKKKCMMMMMMMMNNNNNNNNNNNNOOOOOOOOOOOOOOOOOOOOOOEDDPPPPDDDDRRRRRPPPPPPPPPPPPPPPPPPPPPPFFFFJJJJJXOOOOOOOCCCC
LUULUUUUUUUUUUUUUUPPPPPPPPPPOOTTTTTTKKMMMMIMCCCNNNNNNNNNNNNNNOOOOOOOOOOOOOOOOOOOOODDPPPPDDDDDRRRRRPPPPPPPPPPPPPPPPPPPPPPFJJJJJJJJJJOOOCCCCCC
DUUUUUUUUUUUUUUAPPPPPPPPPPTTTTTTTTTTKMMMMMMMCCCCNNNNNNNNNNNNOOOOOOOOOOOOOOOOOOOOOOODDDDDDDDDRRRRRRRPPPPPPPPPPPPPPPPPPPPPJJJJJJJJJJJOOCCCCCCC
DDDUUUUUUUUUUCCPPPPPPPPPPPPTTTTTTTTTTMMWWWWMCCCCNNNNNNNNNKOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDDDDRRRRPPPPPPPPPPPPPPPPPPPPPPPAJJJJJJJJCCCCCCCCCCC
;

run;
